build:
  version: "1.0"

cards:
  message: "Welcome to EazyBank a related cards Production APIs "
  contactDetails:
    name: "Gautham - QA"
    email: "gautham@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345