build:
  version: "2.0"

loans:
  message: "Welcome to EazyBank a related loans QA APIs "
  contactDetails:
    name: "Smitha - QA"
    email: "smitha@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345